# .github/workflows/rollback.yml
name: Rollback Infra

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag da versão de rollback (ex: infra-v1.0)'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Rollback
        run: terraform plan -input=false -var-file="prod.tfvars"
