# values.yaml - configuração personalizada para o NGINX Ingress Controller
controller:
  replicaCount: 2
  service:
    type: LoadBalancer
  metrics:
    enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
